name: "mddblog"
description: "Blog cá»§a MDD."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  get: ^4.7.2
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  flutter_spinkit: ^5.2.2
  flutter_inappwebview: ^6.1.5
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.0.0-alpha.0
  app_links: ^6.0.2
  google_sign_in: ^7.2.0
  image_picker: ^1.2.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  cloudinary_sdk: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-VariableFont_wght.ttf
  assets:
    - assets/
    - assets/banner/
    - assets/icons/
    - assets/svg/
    - .env
    

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  remove_alpha_ios: true

